import type { Metadata } from "next";
import "./globals.css";
// import { AuthProvider } from "@/context/AuthContext";
import { AuthenticationProvider } from "@/context/AuthenticationContext";

export const metadata: Metadata = {
  title: "Couch Potato",
  description: "Generated by create next app",
  icons: "images/logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative isolate w-full min-h-screen flex flex-col">
        <AuthenticationProvider>
          <main className="grow container mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-16">
            {children}
          </main>
        </AuthenticationProvider>
      </body>
    </html>
  );
}
